name: chicken_tracker
description: Chicken Tracker app with Android V2 embedding.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  google_mobile_ads: any
  shared_preferences: any

flutter:
  uses-material-design: true
